// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvx-2oqc_mfn0G_2EjoymeZaToP0o5UWo',
    appId: '1:784777335858:web:4df09dc101d380c623582b',
    messagingSenderId: '784777335858',
    projectId: 'busy-bee-54b81',
    authDomain: 'busy-bee-54b81.firebaseapp.com',
    storageBucket: 'busy-bee-54b81.appspot.com',
    measurementId: 'G-E2QTXB5EEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvLW6t2VqP3tP6TJI70QQ_YhAdJ806Woo',
    appId: '1:784777335858:android:7959b297d9090db723582b',
    messagingSenderId: '784777335858',
    projectId: 'busy-bee-54b81',
    storageBucket: 'busy-bee-54b81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzb8h2gFbqLFTkXO7M6JhUpMM24JxlDhM',
    appId: '1:784777335858:ios:3946e018e53902ae23582b',
    messagingSenderId: '784777335858',
    projectId: 'busy-bee-54b81',
    storageBucket: 'busy-bee-54b81.appspot.com',
    iosClientId: '784777335858-h77he8nolrsjfftqnsuu1nlufafpdbv7.apps.googleusercontent.com',
    iosBundleId: 'com.example.busyBee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzb8h2gFbqLFTkXO7M6JhUpMM24JxlDhM',
    appId: '1:784777335858:ios:3946e018e53902ae23582b',
    messagingSenderId: '784777335858',
    projectId: 'busy-bee-54b81',
    storageBucket: 'busy-bee-54b81.appspot.com',
    iosClientId: '784777335858-h77he8nolrsjfftqnsuu1nlufafpdbv7.apps.googleusercontent.com',
    iosBundleId: 'com.example.busyBee',
  );
}
